defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/node:8
      environment:
        NPM_CONFIG_LOGLEVEL: error # make npm commands less noisy
        JOBS: max # https://gist.github.com/ralphtheninja/f7c45bdee00784b41fed

restore_cache_keys: &restore_cache_keys
  keys:
    - code-{{ .Branch }}-{{ checksum ".nvmrc" }}-{{ checksum "package.json" }}
    - code-master-{{ checksum ".nvmrc" }}-{{ checksum "package.json" }}

# create "done" jobs, which are just triggered when its dependencies are ran
defaults_done: &defaults_done
  <<: *defaults
  steps:
    - run: echo 'VERY SUCCESS!'

version: 2
jobs:
  test_node:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache_keys
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: ./node_modules/.bin/codecov
      - save_cache:
          key: code-{{ .Branch }}-{{ checksum ".nvmrc" }}-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  test_all:
    jobs:
      - test_node
